[email]
; subject_1 is required. If subject_2 is missing(make sure not empty else your mail subject is empty, if not in use then remove entirely), subject_1 is used for all emails.
subject_1 = Full Stack Developer Application | Job Application
subject_2 = not in use then remove entirely
; reply_to is optional. If omitted in the template, the app uses the sidebar value.
reply_to =
body = Hello {name},
 
 Thank you for your time.
 Please find my resume attached for your review.
 
 Regards,
 Your Name
